export const SUBCATEGORIES_BY_TYPE: Record<string, string[]> = {
  stay: [
    'villa',
    'private_room',
    'boutique_hotel',
    'lodge_camp',
    'hostel',
    'unique_stay',
  ],
  experience: [
    'safari',
    'outdoor',
    'beaches',
    'restaurants',
    'cultural',
    'wellness',
    'family',
  ],
  event: [
    'parties',
    'festival',
    'art_culture',
    'wellness_sport',
    'networking',
    'kids',
    'other',
  ],
  service: [
    'rentals',
    'transfers',
    'private_chef',
    'wellness_service',
    'supermarkets',
    'pharmacy',
    'fundis',
    'it_marketing',
    'utility_shops',
  ],
  real_estate: [
    'for_sale',
    'land_plots',
    'commercial',
    'new_developments',
  ],
}

export const SUBCATEGORY_LABELS: Record<string, string> = {
  // Stays
  villa: 'Villas',
  private_room: 'Private Rooms',
  boutique_hotel: 'Boutique Hotels',
  lodge_camp: 'Lodges & Camps',
  hostel: 'Hostels',
  unique_stay: 'Unique Stays',
  // Experiences
  safari: 'Safari',
  outdoor: 'Outdoor',
  beaches: 'Beaches',
  restaurants: 'Restaurants',
  cultural: 'Cultural',
  wellness: 'Wellness',
  family: 'Family',
  // Events
  parties: 'Parties',
  festival: 'Festivals',
  art_culture: 'Art & Culture',
  wellness_sport: 'Wellness & Sport',
  networking: 'Networking',
  kids: 'Kids',
  other: 'Other',
  // Services
  rentals: 'Rentals',
  transfers: 'Transfers',
  private_chef: 'Private Chef',
  wellness_service: 'Wellness',
  supermarkets: 'Supermarkets',
  pharmacy: 'Pharmacy',
  fundis: 'Fundis',
  it_marketing: 'IT & Marketing',
  utility_shops: 'Utility Shops',
  // Real Estate
  for_sale: 'For Sale',
  land_plots: 'Land & Plots',
  commercial: 'Commercial',
  new_developments: 'New Developments',
}

export const SUBCATEGORY_ICONS: Record<string, string> = {
  villa: '🏡',
  private_room: '🛏️',
  boutique_hotel: '🏨',
  lodge_camp: '⛺',
  hostel: '🎒',
  unique_stay: '🌳',
  safari: '🦁',
  outdoor: '🧗',
  beaches: '🏖️',
  restaurants: '🍽️',
  cultural: '🎭',
  wellness: '🧘',
  family: '👨‍👩‍👧',
  parties: '🎉',
  festival: '🎪',
  art_culture: '🎨',
  wellness_sport: '🏃',
  networking: '🤝',
  kids: '🧸',
  other: '✨',
  rentals: '🚗',
  transfers: '✈️',
  private_chef: '👨‍🍳',
  wellness_service: '💆',
  supermarkets: '🛒',
  pharmacy: '💊',
  fundis: '🔧',
  it_marketing: '💻',
  utility_shops: '🏪',
  for_sale: '🏠',
  land_plots: '🌍',
  commercial: '🏢',
  new_developments: '🏗️',
}
