-- 051_reservations_guest_email.sql
-- Adds guest_email to reservations.
-- Email is now the primary guest notification channel as of Prompt 8c.
-- The wa.me deep links (generated by _lib/whatsapp.ts) remain as a manual fallback
-- shown to owners in the dashboard.
-- When WhatsApp Business API integration ships (future prompt), email and WhatsApp
-- will run in parallel — email is not replaced, it becomes one of two channels.

ALTER TABLE reservations
  ADD COLUMN IF NOT EXISTS guest_email text;  -- ACTIVE V1 (added when email channel became primary)
